create table if not exists public.products (
  id bigint generated by default as identity primary key,
  brand text not null,
  name text not null,
  price numeric(10,2) not null,
  original_price numeric(10,2),
  badge text,
  badge_dark boolean not null default false,
  gradient_from text not null default '#E8D0C0',
  gradient_to text not null default '#C9956A',
  rating numeric(3,2) not null default 0,
  review_count integer not null default 0,
  category text not null,
  description text,
  how_to_apply text,
  ingredients text,
  image text,
  stock integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.product_shades (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  name text not null,
  color text not null default '#C9956A'
);

create table if not exists public.product_finishes (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  name text not null
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'user' check (role in ('admin', 'user')),
  name text,
  email text,
  phone text,
  address text,
  postcode text,
  city text,
  country text default 'Portugal',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists phone text;
alter table public.profiles add column if not exists address text;
alter table public.profiles add column if not exists postcode text;
alter table public.profiles add column if not exists city text;
alter table public.profiles add column if not exists country text default 'Portugal';

create table if not exists public.user_accounts (
  id bigint generated by default as identity primary key,
  role text not null check (role in ('admin', 'user')),
  name text not null,
  email text not null unique,
  username text unique,
  password_hash text not null,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.product_shades enable row level security;
alter table public.product_finishes enable row level security;
alter table public.profiles enable row level security;
alter table public.user_accounts enable row level security;

drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products"
on public.products for select
using (is_active = true);

drop policy if exists "Public can read product shades" on public.product_shades;
create policy "Public can read product shades"
on public.product_shades for select
using (
  exists (
    select 1 from public.products
    where products.id = product_shades.product_id
    and products.is_active = true
  )
);

drop policy if exists "Public can read product finishes" on public.product_finishes;
create policy "Public can read product finishes"
on public.product_finishes for select
using (
  exists (
    select 1 from public.products
    where products.id = product_finishes.product_id
    and products.is_active = true
  )
);

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile"
on public.profiles for select
using (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles for update
using (auth.uid() = id)
with check (
  auth.uid() = id
  and role = (
    select profiles.role
    from public.profiles
    where profiles.id = auth.uid()
  )
);

drop policy if exists "Service role manages profiles" on public.profiles;
create policy "Service role manages profiles"
on public.profiles for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

drop policy if exists "Service role manages user accounts" on public.user_accounts;
create policy "Service role manages user accounts"
on public.user_accounts for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, role, name, email)
  values (
    new.id,
    'user',
    coalesce(
      new.raw_user_meta_data->>'name',
      new.raw_user_meta_data->>'full_name',
      split_part(new.email, '@', 1)
    ),
    new.email
  )
  on conflict (id) do update
  set
    name = coalesce(public.profiles.name, excluded.name),
    email = excluded.email,
    updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

drop policy if exists "Public can read product images" on storage.objects;
create policy "Public can read product images"
on storage.objects for select
using (bucket_id = 'product-images');
