create table if not exists public.products (
  id bigint generated by default as identity primary key,
  brand text not null,
  name text not null,
  price numeric(10,2) not null,
  original_price numeric(10,2),
  badge text,
  badge_dark boolean not null default false,
  gradient_from text not null default '#E8D0C0',
  gradient_to text not null default '#C9956A',
  rating numeric(3,2) not null default 0,
  review_count integer not null default 0,
  category text not null,
  description text,
  how_to_apply text,
  ingredients text,
  image text,
  stock integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.product_shades (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  name text not null,
  color text not null default '#C9956A'
);

create table if not exists public.product_finishes (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  name text not null
);

alter table public.products enable row level security;
alter table public.product_shades enable row level security;
alter table public.product_finishes enable row level security;

drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products"
on public.products for select
using (is_active = true);

drop policy if exists "Public can read product shades" on public.product_shades;
create policy "Public can read product shades"
on public.product_shades for select
using (
  exists (
    select 1 from public.products
    where products.id = product_shades.product_id
    and products.is_active = true
  )
);

drop policy if exists "Public can read product finishes" on public.product_finishes;
create policy "Public can read product finishes"
on public.product_finishes for select
using (
  exists (
    select 1 from public.products
    where products.id = product_finishes.product_id
    and products.is_active = true
  )
);

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

drop policy if exists "Public can read product images" on storage.objects;
create policy "Public can read product images"
on storage.objects for select
using (bucket_id = 'product-images');
